version: "3"

services:
  node:
    image: "node:18"
    user: "node"
    working_dir: /app
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app
    ports:
      - "5173:5173"
    command: "sleep infinity"
